### ISSUE TITLE
Gutenberg isn't supported

### ISSUE THREAD

**Issue by pento** [danieltj27/Dark-Mode#108]
Apart from a few random CSS rules that are obeyed, Gutenberg mostly appears in light mode.

**Comment by danieltj27** [comment]
Please see [issue 7645](https://github.com/WordPress/gutenberg/issues/7645#issuecomment-401621749). It'd be good to try and coordinate release dates of Gutenberg and Dark Mode as I don't think supporting Gutenberg is worth while until it's at very close to feature complete as it's a huge task and there's lots changing on a regular basis.

I'll need to chat to you and the rest of the core team at some point about how to approach this.

**Comment by pento** [comment]
You should consider Gutenberg to be very close to feature complete. There may still be some changes, but nothing huge, and certainly easy enough to test for and tweak.

The `is-dark-theme` class is related, but different: it's for dark themes to define themes styles. Dark Mode would probably need to take into account the difference between dark and light themes, as the block editor area is supposed to be WYSIWYG-ish.

There's an interesting discussion to be had over which order rules should be obeyed: block editor default styles, theme-specific styles, and Dark Mode styles. I suspect the best option would be to make the chrome surrounding the block editor dark, then override block editor default styles, but don't override theme-specific styles. That might get janky when the theme specifies a text colour but not a background colour, though.

**Comment by hedgefield** [comment]
Oh yeah that's a tricky one, when theme styles are applied to the editor.. Perhaps a toggle in the More menu would be good, similar to the dock/undock of the toolbar, so you can quickly switch between dark-writing-mode and normal-check-theme-styling mode.

**Comment by danieltj27** [comment]
Related to #43 which was closed a while ago.

**Comment by danieltj27** [comment]
Long time no comment on here from me but I think that personally, as it's not in core yet, Dark Mode won't support Gutenberg. I think the best approach is for Gutenberg to support Dark Mode as this way I (and the the Gutenberg core team) can work together on getting the dark styles integrated into WordPress core properly rather than relying on Dark Mode to try and do it which may cause issues.

This also means there isn't the pressure of trying to keep up with Gutenberg which right now, is changing rapidly every week.

I'll need to update some core files to remove the (very small) steps already made to support Gutenberg. From there we can go to a merge proposal and discuss further. I'll close this for now and will re-open in the future if needs be.
