### ISSUE TITLE
Consider support for prefers-color-scheme media query

### ISSUE THREAD

**Issue by johnbillion** [danieltj27/Dark-Mode#130]
Ref: https://twitter.com/Keithamus/status/1055179677277384705

Safari Tech Preview now supports a `prefers-color-scheme: dark` CSS media query that is used when macOS  Mojave is in dark mode. It would be interesting to consider how to support this in the Dark Mode plugin.

Considerations:

* Should this media query override the user's chosen setting in their profile?
* How does this affect the build process and stylesheet loading?

**Comment by danieltj27** [comment]
Thanks for adding this one John.

This is tricky because it sort of conflicts with how Dark Mode is decided whether it should be activated or not at the moment. I'm thinking that perhaps the setting should still be required for Dark Mode to be enabled, but then have another setting to say obey the `prefers-color-scheme` rule. Although that still presents a problem in turning it on/off via CSS.

It's one I need to have a think about. I'm open to suggestions.

**Comment by danieltj27** [comment]
This is related to issue #112.

**Comment by danieltj27** [comment]
[See #151 for more info](https://github.com/danieltj27/Dark-Mode/issues/151).
