### ISSUE TITLE
Missing screenshots

### ISSUE THREAD

**Issue by tomjn** [danieltj27/Dark-Mode#27]
there are no screenshots for the .org plugin page! :(

**Comment by danieltj27** [comment]
I missed screenshots out until the dashboard homepage was styled properly but now it is I probably should make some. If anyone else wants to do a few feel free! 👍

**Comment by danieltj27** [comment]
This has been fixed in commit c3c0e9a (kind of). Screenshots are not part of the plugin package and are done separately for the plugin directory so they won't appear here.

As future reference, if anyone wants to do more/better screenshots then feel free, just make sure you do a pull request with the updated screenshot text in the plugin `readme.txt` file.

Screenshots can be found here: http://plugins.svn.wordpress.org/dark-mode/assets/
