### ISSUE TITLE
Dark Mode Dreams

### ISSUE THREAD

**Issue by Presskopp** [danieltj27/Dark-Mode#30]
Hi,

while I can see the plugin is still in it's baby shoes I have some ideas/notes/questions:

Will this be playing nicely in combination with user color schemes?
Will it override it or somehow combine?

Would be nice to be able to set a time schedule for de/enabling the dark mode and if you allow me to dream more, this could even be available as an automatic mode, checking the user's time zone (or even sunset time query?)

When dark mode gets enabled, it should fade in, not switch from white to dark instantly..
Maybe having -not so dark- mode first, 1h later full darkness

PS: While developing, it would be helpful to have the darkmode.css file uncompressed

**Comment by danieltj27** [comment]
Thanks for sharing your thoughts on this. I have thought about implementing a timer for it to come on automatically - that'd be nice.

To answer your questions though:
1. User colour schemes are not touched/overridden and can still be used when Dark Mode is turned on by someone.
2. Dark Mode CSS has no control over any colour schemes so you can expect to see the red or purple colours (as an example) just as they'd normally appear.

As for having the dark colours fade in and have them get darker over time, that might be too difficult to implement as at the moment it's just overriding colours with the darker versions as opposed to making the colours on screen a percentage darker. So that would be tricky.

**Comment by danieltj27** [comment]
Added the ability to automatically turn it on at certain times in commit d791ba9.

**Comment by danieltj27** [comment]
I forgot to ask, @Presskopp let me know if you want your name added to the contributors list or not. I'm happy to add you on there.

**Comment by Presskopp** [comment]
Well if you feel like I don't say no - thank you :)

**Comment by danieltj27** [comment]
No worries, I've made some changes based on the ideas above in commit a4d7179.
