### ISSUE TITLE
Let's discuss workflow ideas

### ISSUE THREAD

**Issue by Presskopp** [danieltj27/Dark-Mode#38]
I propose to show the 'Dark Mode Menu' if the plugin is installed/active
![1](https://user-images.githubusercontent.com/18373563/33240221-161135d4-d2b3-11e7-8f76-bce04876a306.jpg)

The current state could be shown:
![2](https://user-images.githubusercontent.com/18373563/33240226-2ed2ca06-d2b3-11e7-8ad9-01e57c47b93a.jpg)

If on automatic it would show auto:
![3](https://user-images.githubusercontent.com/18373563/33240233-43812362-d2b3-11e7-8dff-40d960a5cb5a.jpg)

Show feedback as submenu (if not disabled via define false)
![5](https://user-images.githubusercontent.com/18373563/33240241-697c579e-d2b3-11e7-8144-0500135b12a1.jpg)

![4](https://user-images.githubusercontent.com/18373563/33240246-72a4ccf2-d2b3-11e7-9b3a-48550eadc11a.jpg)
What if set to auto, but not enabled? Auto could be a alternative choice overriding this, so it would still be active, or the auto setting could be hidden/inactive if the 'Enable..' checkbox is not set!?

If you click on 'Dark Mode', it could be a link to the profile, or would we like a 'toggle on/off' ?

We could also rename the setting to 'Show Dark Mode on the admin dashboard'

I'd love to discuss this and find a safe route..

**Comment by munyagu** [comment]
I like toggle on/off.

Plugin with an admin page that reflects its own CSS, the contrast may be too large for the element.
In such cases I want to switch on/off temporarily without switching the screen.

**Comment by danieltj27** [comment]
I like the idea behind this - I think from a language perspective we should stay clear of the word toggle though as I saw in the Make WordPress Slack that `toggle` appeared as a string to translate in Core and some Polyglots couldn't translate it effectively. But I think the direction for this is a good way to go.

The only thing I oppose here though is turning Dark Mode on/off from the toolbar directly as it's a profile option because it is very much an aesthetics setting rather than functionality so it's not critical to be at the forefront. 

If we can work on a way of making sure that's made clear somehow by perhaps an icon with text to illustrate then that'd work. I'm no against having anything in the toolbar, but the off/on functionality definitely needs to stay on the edit profile page I think.

**Comment by danieltj27** [comment]
Closing - addressed in PR #41.
